### ISSUE TITLE
6月3号后直播间不再能收到弹幕消息，可能b站有更新

### ISSUE THREAD

**Issue by 15so42** [Executor-Cheng/SimpleBilibiliDanmakuClient#1]
能麻烦检查并更新一下吗，非常感谢

**Comment by Executor-Cheng** [comment]
本项目不负责消息解析
所以你需要在你的代码中, 修改订阅 `ReceivedMessageEvt` 事件的相应方法
修改其中解析cmd的语句, 其值在6月3，4，5号期间应为以 `DANMU_MSG` 开头的字符串
比如:
https://github.com/copyliu/bililive_dm/blob/717cacde11870e07b5ab4ccfccec02948bee5ee4/BilibiliDM_PluginFramework/DanmakuModel.cs#L469

**Comment by 15so42** [comment]
感谢回复，我已经用了一个多月你的项目，直到昨天晚上都是可用的。
因为听说是b站在维护我就没管，直到刚才看了你的回复，回去Debug的时候才发现cmd的type从DANMU_MSG变为了DANMU_MSG:4:0:2:2:2:0 我改成新的type后可读了。不过其实只需要像你的代码一样改成startsWith就好了，我用的是case，所以有这个问题。之后也改成StartsWith,再次感谢
